### ISSUE TITLE
Unable to run OFS through Snap

### ISSUE THREAD

**Issue by NodudeWasTaken** [OpenFunscripter/OFS#10]
Hello Gagax!

I am running manjaro linux with an nvidia gpu, and am having severe issues running OFS.
When running OFS it for some reason finds no video devices?
Then if i bypass that, it cannot find the mpv library?
My current install runs through snap, but i did try manually compiling it, which didnt fix the missing video device.
```
$ glxinfo |grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 470.63.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 470.63.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 470.63.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

$ openfunscripter
WARN: "/home/username/snap/openfunscripter/x1/.local/share/OFS/OFS_data/config.json" doesn't exist
ERROR: Error: No available video device
[1]    3191076 segmentation fault (core dumped)  openfunscripter

$ export SDL_VIDEODRIVER=dummy
$ openfunscripter
WARN: "/home/username/snap/openfunscripter/x1/.local/share/OFS/OFS_data/config.json" doesn't exist
ERROR: Failed to load "libmpv.so.1"
ERROR: Failed to load mpv library.
[1]    3226164 segmentation fault (core dumped)  openfunscripter

$ ls /usr/lib | grep -i mpv
libmpv.so
libmpv.so.1
libmpv.so.1.109.0
```

Thanks,
Nodude

**Comment by michael-mueller-git** [comment]
@NodudeWasTaken I can run OFS compiled from source without problem on my manjaro test system with nvida gpu. I don't have problems with missing video device here. But i can confirm the problems with the snap pack. I get the same errors.  When yo compile form source make sure you open the compiled binary and not the snap.

**Comment by OpenFunscripter** [comment]
I havn't tested the snap in a while.
I'm going to get rid of it and will replace it with an AppImage instead.
Yesterday I managed to create an AppImage on fedora and run it on a clean installation ubuntu without having mpv on the system.
I just have to automate the process via github actions.

**Comment by NodudeWasTaken** [comment]
After a quick test i can verify that @michael-mueller-git was right in that i accidentally launched the snap version instead of the compiled one.
The compiled version works perfectly, my only grievance was that i had to make a .desktop file myself.
I could close this issue now, but the snap version is still broken, so im leaving it up to you @OpenFunscripter

**Comment by OpenFunscripter** [comment]
I added an AppImage to the current tagged release.
Can you run this on your system? Make sure to `chmod +x *.AppImage` first.
I stopped trying to include a version of mpv in the AppImage itself as it was causing too many problems.
So the AppImage will just load the libmpv.so.1 installed on your system.
I think this is better than the snap but it requires the user to install libmpv via their package manager.
https://github.com/OpenFunscripter/OFS/releases/tag/1.4.2

**Comment by michael-mueller-git** [comment]
The AppImage works for me (operating system: arch linux).

**Comment by NodudeWasTaken** [comment]
I can run the AppImage :smile: (operating system: manjaro)

**Comment by OpenFunscripter** [comment]
I guess that way everybody gets to use the version of mpv which ships with their distro.
I'm going to stop adding the snap packages then since they never worked perfectly.
