### ISSUE TITLE
Feature Request: Gamepad joystick configuration

### ISSUE THREAD

**Issue by LT-Dangle** [OpenFunscripter/OFS#11]
Would like to be able to set move actions to gamepad joystick movements.

**Comment by OpenFunscripter** [comment]
I don't know what this means.

If you mean the ability to bind the analog stick movements to arbitrary actions in the Keybinding window.
It might be possible.

Question then is how many directions should be possible?
Probably just north, east, south & west...
![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Brosen_windrose.svg/1024px-Brosen_windrose.svg.png)

**Comment by OpenFunscripter** [comment]
Binding the analog stick directions N,E,S,W is going to be possible in the next version.
