### ISSUE TITLE
Glibc_XX

### ISSUE THREAD

**Issue by oletoc88** [OpenFunscripter/OFS#12]
Hello
When I try to run OFS-64X_xxxxx.appimage from terminal in ubuntu 16.04, tell me:
Desktop$ ./OFS-64x_8c11bba818bf18acd8d154fb1b138cbc58cb27f9.AppImage
/tmp/.mount_OFS-64cPrRhq/usr/bin/OpenFunscripter: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_OFS-64cPrRhq/usr/bin/OpenFunscripter)
/tmp/.mount_OFS-64cPrRhq/usr/bin/OpenFunscripter: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_OFS-64cPrRhq/usr/bin/OpenFunscripter)

Requires old libraries.

**Comment by OpenFunscripter** [comment]
This looks more like it requires **new** libraries.
Maybe there's some static linking which can be done...

**Comment by OpenFunscripter** [comment]
Closing this because I don't want do dive into this.
