### ISSUE TITLE
Feature request: Open project file when project file is found during importing video/script

### ISSUE THREAD

**Issue by trassshhub** [OpenFunscripter/OFS#15]
When a project file is found during video/script import, OFS will fail to import and shows an alert.
The user has to manually open the project from the menu.
It would be better if the user is offered a choice to open the project file.

**Comment by OpenFunscripter** [comment]
Nothing against this just have to find the time to add this.

**Comment by OpenFunscripter** [comment]
This also turned out to be rather simple.
