### ISSUE TITLE
OFS is forcibly terminated when some videos are played. (OpenGL error INVALID_VALUE.)

### ISSUE THREAD

**Issue by Dunk52** [OpenFunscripter/OFS#17]
Hello, 
When a specific video is played, OFS is forced to close after 30 seconds.

OFS 1.4.3 version is being used.

OFS.log
```
[ 0.434][INFO ]: Opening video: "C:\Users\USER\Downloads\videoname.mp4"
[ 0.455][INFO ]: Font atlas was rebuilt. Took 0.003 seconds.
[ 0.455][INFO ]: New font atlas size: 512x512
[ 0.473][INFO ]: Active hardware decoder: no
[info][MPV] (cplayer):  (+) Video --vid=1 (*) (h264 1280x720 60.000fps)
[info][MPV] (cplayer):  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[info][MPV] (display-tags): File tags:
[info][MPV] (display-tags):  Artist: VideoProc
[info][MPV] (display-tags):  Comment: 
[info][MPV] (display-tags):  Genre: 
[info][MPV] (display-tags):  Title: 
[info][MPV] (cplayer): AO: [wasapi] 48000Hz stereo 2ch float
[info][MPV] (cplayer): VO: [libmpv] 1280x720 yuv420p
[error][MPV] (libmpv_render): after creating texture: OpenGL error INVALID_VALUE.
```

Windows Specifications
OS :  Windows11 Dev(OS build 22543.1000)
CPU : i7-9700F
Memery : 32GB
GPU : GTX 1070

Video spec
![image](https://user-images.githubusercontent.com/28643783/151928848-3de09332-d8ba-4806-bbb1-c737a5b7cea2.png)

(I used Google Translator to translate it.)

**Comment by Dunk52** [comment]
OK, Thanks.

However, I think I found the cause a little through several tests.
Symptoms are forced to end every 60 seconds.
When Auto Backup was disabled (unchecked), the symptoms disappeared.
And after 60 seconds, Auto Backup was directly activated, so it was forcibly terminated immediately.

We will disable Auto Backup and work until the bug is fixed.
(I used Google Translator to translate it.)

**Comment by OpenFunscripter** [comment]
Closing this
