### ISSUE TITLE
Double click to seek gone beyond 1.4.0

### ISSUE THREAD

**Issue by f86k** [OpenFunscripter/OFS#20]
I have 1.4.0, 1.4.2, and 1.4.3 installed (so perhaps it still works on 1.4.1, haven't tried that). I can only double-click to seek within the Positions bar with 1.4.0. Is this intentional?

**Comment by OpenFunscripter** [comment]
Yes, actually.
I moved it two double middle mouse click.

The intent was to be able to seek without clearing the selection.
Only after creating a new release I realized that I was using single middle mouse click to clear the selection. 🤦‍♂️
So that was rather pointless...

**Comment by OpenFunscripter** [comment]
I think I kept this open because I wanted to revert this change 🤨

**Comment by OpenFunscripter** [comment]
Well it sure took a while but it's reverted on the `state-rewrite` branch.
And it also doesn't clear the selection anymore either...

Didn't even mean to do this but I was in the area so to speak. 😎
