### ISSUE TITLE
Crashes when most recent file has non-ASCII characters

### ISSUE THREAD

**Issue by space-nuko** [OpenFunscripter/OFS#22]
A file like `1.音声ファイル` becomes garbled as `1.éŸ³å£°ãƒ•ã‚¡ã‚¤ãƒ«` and it crashes when trying to open a project. (on Windows)

**Comment by OpenFunscripter** [comment]
I wish I could reproduce this.
But it doesn't happen for me (on 1.4.3).

**Comment by space-nuko** [comment]
I made a patch myself, it was an issue with wide path encodings.
