### ISSUE TITLE
SDL_GetBasePath returns wrong path on macOS 

### ISSUE THREAD

**Issue by NodudeWasTaken** [OpenFunscripter/OFS#23]
https://wiki.libsdl.org/SDL_GetBasePath
In the documentation, it reads that CMake on macOS defaults to ".app/Contents/Resources", as can be seen in this path: "OpenFunscripter.app/Contents/Resources/data/fonts/RobotoMono-Regular.ttf".
This is wrong as the font gets placed in "OpenFunscripter.app/Contents/MacOS/data/fonts/RobotoMono-Regular.ttf".
Funny enough there is a Resources folder with /data/lua in it, but no files.

Also there is no icon, macOS is weird.
Maybe there can now finally come a macOS build, and the quarterly post of "macos scripter plz" will finally be resolved.

**Comment by OpenFunscripter** [comment]
Well I don't quite follow, but isn't it more like the font is placed in the wrong directory rather than `SDL_GetBasePath` returning the wrong path?
I'm not familliar with any of this. 

Here's what I know:  
- OFS compiles on macOS

No more, no less. Sorry 😥

**Comment by OpenFunscripter** [comment]
@NodudeWasTaken does the patch by @MarshMongoose help you?

**Comment by NodudeWasTaken** [comment]
It does :)
2 issues left, 
1. No icon, this isn't too serious.
2. Open project is also broken on macOS, if i find a solution i'll submit a patch, otherwise i'll just open another issue ;D
