### ISSUE TITLE
Feature request: Shift+ScrollWheel

### ISSUE THREAD

**Issue by Rakly3** [OpenFunscripter/OFS#31]
I've been trying to use my own little script but it's messing with normal typing.

Could it be added that Shift + WheelUp and WheelDown moves the actiondot up/down
Same way as Shift+Up and Down do.

Maybe even Ctrl+WheelUp/Down moves the dot left/right

As Ex-gamer, using WASD for up/down/left/right would be sweet too! (Though for me it would have to be ZQSD (AZERTY keyb)

Thanks!

**Comment by OpenFunscripter** [comment]
I would add this by making it possible to use the mouse buttons (scroll wheel is considered a mouse button) in the keybinding settings.
This would enable all those things except you would be overriding the default keyboard shortcuts.
This means you wouldn't be able to have both Shift+Up and Shift+MouseWheelUp at the same time. 

>using WASD for up/down/left/right would be sweet too!

All those things are already rebindable to whatever you want so you can already do this right now.

**Comment by Rakly3** [comment]
> > using WASD for up/down/left/right would be sweet too!
> 
> All those things are already rebindable to whatever you want so you can already do this right now.

Sorry, I must have looked over it!

**Comment by OpenFunscripter** [comment]
I added this but there are still some problems.
Like scrolling over the timeline will zoom while also triggering the keybinding.
But that's a problem for future me
