### ISSUE TITLE
Change waveform appearance

### ISSUE THREAD

**Issue by Jimmy3111** [OpenFunscripter/OFS#32]
My audio wave became this since don't know which version.
![image](https://user-images.githubusercontent.com/86543261/172832961-c0098a2a-b4a8-45aa-92c8-9a9940ac3946.png)

Is there a way to force it back to this appearance? It is very hard for me to read the waveform with the new waveform appearance.
![image](https://user-images.githubusercontent.com/86543261/172833201-715d5faf-484c-4c06-9423-0833cf52de51.png)

**Comment by OpenFunscripter** [comment]
I don't thinkg it has anything to do with the new rendering.
You can use the the scale factor to make things more visible.
![Capture](https://user-images.githubusercontent.com/86110971/172931488-d3124dba-d9bc-4fda-b86b-c4721c977029.PNG)

I used to normalize the samples before displaying them. Currently I'm just displaying them as they are.
Normalizing can improve the default scale but it can also make it worse. 🤔

Ultimately it depends on the audio if it's all low frequency there's nothing to render.

**Comment by OpenFunscripter** [comment]
I added back the normalization.
That way the default scale will be better in a lot of cases and in the ones where it isn't you'll have to manually tweak the scale either way.

**Comment by Jimmy3111** [comment]
Thanks for adding the normalization back...

**Comment by Jimmy3111** [comment]
Sorry, maybe I was not explaining my question clearly. After the update, I don't see any difference. (Maybe the scale is easier to adjust now? I am not sure what it means by normalization.) Scale is never the problem. What I was asking before is the look of the waveform. I make a comparison for two version of waveform at the same scale (5.0) and timestamp. Maybe it can help u understand my question easier. 

As you can see, the waveform of the old version (1.3.0) shows more audio details. Also, it is very hard to see in the new version as the peak is so thick. They overlapped with each other.

![image](https://user-images.githubusercontent.com/86543261/179759264-94802454-8ca8-4088-a41d-b819452b296a.png)

![image](https://user-images.githubusercontent.com/86543261/179759331-13f23f00-7d8d-44ae-b98d-73c7faf3b3d5.png)

Sorry for not explaining myself clearly and Thank you for adding normalization for me particularly. Pls consider adding the old waveform option in the next update if it is not too much trouble.

**Comment by OpenFunscripter** [comment]
I'm going to have another look.
But I'm not bringing back the old style.
That alone wouldn't do anything anyway since it would just display the data below in a different style.

The benchmark for how it looks shouldn't be OFS 1.3.0.
Instead it should be some other program which I can trust to generate a "correct" waveform image.

There both approximations but I wonder which version above is closer to the "correct" image.

**Comment by OpenFunscripter** [comment]
I found the issue ...
