### ISSUE TITLE
Feature Request: Ability to copy strokes from one script to another 

### ISSUE THREAD

**Issue by Slibowitz** [OpenFunscripter/OFS#33]
Hello!

I made a compilation from various clips. I already scripted these clips and wanted to just copy over the needed parts into the compilation video.

This seems to be unfortunately not be possible with OFS. Instead I had to use JFS for this. JFS copied the marked strokes into a clipboard and I could paste it into the new video.

While this works, and without meaning to say anything bad about JFS, I appreciate OFS now way more overall. So I would love to have the function for OFS as well. 

Would it be possible to add this? Or is there already a way, which I am not aware of?

Thank you very much!

Slibowitz

**Comment by OpenFunscripter** [comment]
`Project` -> `Add...` -> `Add existing`
afterwards
`Project` -> `Remove` -> `...`

Opening multiple instances and copying between them is not supported.
In fact opening multiple instances simultaneously is not supported.

**Comment by Slibowitz** [comment]
And there are no plans or there is no way to make this possible in a future update?

**Comment by OpenFunscripter** [comment]
> `Project` -> `Add...` -> `Add existing`
> afterwards
> `Project` -> `Remove` -> `...`

I just told you how can already do this by adding the script to want to copy from.
Copy from it.
And then remove it again.

I don't seee the problem.
