### ISSUE TITLE
Funscript:selectedIndices() offset by 1

### ISSUE THREAD

**Issue by SleepyPrince** [OpenFunscripter/OFS#34]
https://github.com/OpenFunscripter/OFS/blob/9c93e078358e33d4a0c8aef46cbaa01371d7cb77/src/lua/api/OFS_LuaScriptAPI.cpp#L198-L207
`selectedIndices.emplace_back(i);` should be `selectedIndices.emplace_back(i+1);` ?

**Comment by OpenFunscripter** [comment]
yes you're right
