### ISSUE TITLE
Feature request - Highlight ofs.text

### ISSUE THREAD

**Issue by LimitlessMan36** [OpenFunscripter/OFS#38]
In [My Tool](https://discuss.eroscripts.com/t/my-tools-extension-for-openfunscripter/61434?u=limitlessman), I add all tools 
one above the other and it's difficult to differentiate tool title of other texte.

It was realy useful to have the possibility to put the text bold. Or maybe change the color.
Someting like that :

local bold = true
ofs.Text("Text", bold)

**Comment by OpenFunscripter** [comment]
Sorry but no. I can't add that.
I also don't want to add colored text either.
