### ISSUE TITLE
bug: Simulator rendered on top of top menu

### ISSUE THREAD

**Issue by SleepyPrince** [OpenFunscripter/OFS#40]
Simulator is rendered on top of top menu
![ofs](https://user-images.githubusercontent.com/670216/183406949-4ec665f7-e00b-4c92-afa8-86f8cb3906cc.png)

**Comment by OpenFunscripter** [comment]
I honestly think of this more as a feature than a bug. 😏

**Comment by SleepyPrince** [comment]
Understandable, Have a Nice Day 😏
