### ISSUE TITLE
Jitter (2.0) fix

### ISSUE THREAD

**Issue by Rakly3** [OpenFunscripter/OFS#41]
I don't know where to change this in the master code. I searched but couldn't find.

Jitter in OFS 2.0 not working/error
In main.lua I changed this

 
```
   -- prevent negative or 0
   Jitter.TimeMs = math.max(Jitter.TimeMs, 1)
   Jitter.Position = math.max(Jitter.Position, 1)
   if changedPos or changedTime then
       ofs.Undo() -- ofs.Undo() only undoes changes by Lua scripts never anything else
       jitter()
   end
```

To this

```
    -- prevent negative
    Jitter.TimeMs = math.max(Jitter.TimeMs, 0)
    Jitter.Position = math.max(Jitter.Position, 0)

    if changedPos or changedTime then
        ofs.Undo() -- ofs.Undo() only undoes changes by Lua scripts never anything else
        binding.jitter()
    end
```

and now it's working.

I also suggest adding a button so you can re-apply the same jitter settings if you're not happy with the results, or, if you want to apply the same jitter to a new selection.

```
    if ofs.Button("Apply") then
        ofs.Undo() -- ofs.Undo() only undoes changes by Lua scripts never anything else
        binding.jitter()
    end
```

Time jitter is not working correctly either, changing 1ms seems to be applying 1 second.

Replaced 
`action.at = action.at + time_jitter_value`
with
`action.at = action.at + time_jitter_value / 1000`

**Comment by Rakly3** [comment]
While we're at it

```
    if ofs.Button("Position + 1") then
        ofs.Undo() -- ofs.Undo() only undoes changes by Lua scripts never anything else
		Jitter.Position = Jitter.Position + 1
        binding.jitter()
    end	

    if ofs.Button("Position - 1") then
        ofs.Undo() -- ofs.Undo() only undoes changes by Lua scripts never anything else
		Jitter.Position = Jitter.Position - 1
        binding.jitter()
    end

    if ofs.Button("Undo") then
        ofs.Undo() -- ofs.Undo() only undoes changes by Lua scripts never anything else
    end
```

**Comment by OpenFunscripter** [comment]
I added the fixes but I don't really want to flood the extension with additional buttons.
The true purpose of the Core extension is really just to have some example code.

It's hidden in this source file https://github.com/OpenFunscripter/OFS/blob/eb7919cf8ca30a22a91379a773d3e052c45337dc/src/lua/OFS_LuaCoreExtension.cpp
