### ISSUE TITLE
Feature Request: Changing the unsaved changes dialog logic

### ISSUE THREAD

**Issue by trassshhub** [OpenFunscripter/OFS#42]
The current dialog in OFS on closing project/opening another project while unsaved changes is detected seems not to be in line with conventional logic.

Usually when an unsaved file is getting closed, the Yes/No/Cancel dialog would ask if the user would like to save the file or not:
Yes - Save the changes and close
No - Discard the changes and close
Cancel - Don't close

The current OFS behavior does it the other way round and asks if the use would like to discard the changes:
Yes - Discard the changes and close
No - Don't close (but also won't save the changes)
Cancel - Don't close
which I find confusing.

Also, when drag'n droping another file into OFS when an unsaved project is present, it should be treated as trying to close the current project and load the dropped one. Therefore the same type of dialog shall be shown instead of an alert dialog with "The current project has unsaved edits.".

**Comment by OpenFunscripter** [comment]
This confuses me because when I test this it behaves like you expect.

>Yes - Save the changes and close
No - Discard the changes and close
Cancel - Don't close

The drag'n drop thing can be changed.

**Comment by trassshhub** [comment]
These are the dialogs when you have unsaved edits.
![ofs](https://user-images.githubusercontent.com/94064652/188965974-790679ed-ffeb-4921-a2cc-8ae1532b9d49.png)

1. Close current project/open another project
2. Open project through the recent 
3. Drag and drop file into OFS
4. Close OFS by clicking the X button

only the last example follows what I expected.

**Comment by OpenFunscripter** [comment]
I didn't realize there were two yes/no/cancel dialogs.
I changed the top one to be like the bottom one.
And I added the bahaviour to the file dropping

**Comment by SleepyPrince** [comment]
Thanks for the fix, but I find that the second case (Open project through the recent files menu with unsaved edits) has not been resolved.

**Comment by trassshhub** [comment]
Thanks for the fix, but I find that the second case (Open project through the recent files menu with unsaved edits) has not been resolved.

**Comment by OpenFunscripter** [comment]
Sorry I missed that
