### ISSUE TITLE
Pitch Module gets stuck in the forward position

### ISSUE THREAD

**Issue by miyukialice05** [OpenFunscripter/OFS#45]
While Playing a video with pitch script using the T-Code module, if I keep the pitch value at a steady unmoving 5 every 3 frames, eventually the pitch will creep forward during fast strokes and it does not correct itself. It seems software related because the same script exported to scryptplayer does correct itself back to the 5 position constantly.

**Comment by OpenFunscripter** [comment]
I'm removing T-Code support so this is no longer relevant.
Instead you'll be able to use OFS + MFP for livetesting https://github.com/Yoooi0/MultiFunPlayer/issues/105 😎
