### ISSUE TITLE
Feature request: Overwrite already assigned key pop-up

### ISSUE THREAD

**Issue by Husky5383** [OpenFunscripter/OFS#46]
When you want to add a new key shortcut and it is aleready in use you need to manually find the already assigned key and change it. Instead, there could be an extra option to automatically change the old shortcut to "not-set".

**Comment by OpenFunscripter** [comment]
Agreed.

I need to redo the entire thing because in it's current state there's so much I can't do (specifically #11 & #31). 
Note to self: The checking if a key is already used doesn't include extension bindings. Which needs to be addressed aswell.

**Comment by OpenFunscripter** [comment]
I redid the entire thing and this is now implemented.
