### ISSUE TITLE
Unable to seek to previous action

### ISSUE THREAD

**Issue by trassshhub** [OpenFunscripter/OFS#47]
I was unable to seek back to the previous action if the playback cursor has passed the last action (running 5e37f7ef1faa125150e68f7825a8812246a6f8c9 binary from github Actions). I traced through different binaries and found that during 2e40325274bc99ebd75b19e6389b648831599573, the return logic of getPreviousActionBehind in OFS-lib/Funscript/Funscript.h was changed.

https://github.com/OpenFunscripter/OFS/blob/2e40325274bc99ebd75b19e6389b648831599573/OFS-lib/Funscript/Funscript.h#L186-L195

It seems to work again if I replace line 191-194 with:
`return it - 1 >= data.Actions.begin() ? &*(--it) : nullptr;` (similar to code prior to this commit)

not sure if this is the proper way to fix it.

**Comment by OpenFunscripter** [comment]
I noticed this as well and changed it like this on the [videoplayer-rewrite](https://github.com/OpenFunscripter/OFS/tree/videoplayer-rewrite) branch.
That branch isn't ready to merged into the master yet.
https://github.com/OpenFunscripter/OFS/blob/911c49693c8a3cd4483d436b6319b6a2204f8586/OFS-lib/Funscript/Funscript.h#L191

Checking `it != data.Actions.begin()` should be all that is needed.
