### ISSUE TITLE
Keeping relative path instead of full path in .ofsp

### ISSUE THREAD

**Issue by Zalunda** [OpenFunscripter/OFS#49]
Sometimes, I move all the files that I'm working on (i.e. .ofsp, .mp4, .mp4.optimized, .funscript) to another folder.

Right now, when I do that, I have to reset all the referenced files. I have to set the .funscript path, pick media, etc.

The worse one is the .funscript path because I often forget to set it and the file keeps getting saved in the wrong folder.

It would be nice if the .ofsp contained relative paths to the .ofsp file (ex. ".\file.funscript", ".\file.mp4", etc).

I think this method could be used to transform the path before saving:
https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathrelativepathtoa

**Comment by OpenFunscripter** [comment]
This can be done but it feels like the kind of thing that somebody else isn't going to like.
The reason it's using absolute paths is because I'm lazy.
I'm not opposed to changing it.

**Comment by Zalunda** [comment]
I understand. Peoples work in a way that needs FullPath would be impacted (having all the .ofsp in a single folder and referencing videos and .funscript in another ??). 

I guess it could be implemented by saving the relative path and the full path. When loading, if the relative path is not found, use the full path (and update the relative path) but it would mean more logic in the application. 

Honestly, it's not too bad. I don't move the files often. It just happened a few times where I made changes in a script, saved it, went to test it, and noticed that I didn't have the latest version (because it was saved in the old folder).

**Comment by OpenFunscripter** [comment]
I implemented relative paths.
Media path & funscript paths are relative to the project file.
Will see how it goes.

I think it's more intuitive this way.
