### ISSUE TITLE
Feature request: Line simplification algorithm

### ISSUE THREAD

**Issue by NodudeWasTaken** [OpenFunscripter/OFS#58]
Hello Gagax!

Sometimes when i view scripts, i find that it contains way too many unused points which could be deleted.
This is why i want OFS to implement the Ramer–Douglas–Peucker algorithm (or something similar), which seeks to eliminate points if their "curve difference" is less than some epsilon value.

Thanks

**Comment by OpenFunscripter** [comment]
Uhm this already exists  🤨
Too be fair it's very hidden in the `View->Special functions` window.
