### ISSUE TITLE
Github actions artifacts have broken mpv dll

### ISSUE THREAD

**Issue by Yoooi0** [OpenFunscripter/OFS#60]
Recently noticed that all github action builds seem to contain a broken `mpv-2.dll` so they are not able to run.
`mpv-2.dll` file contents:
```
version https://git-lfs.github.com/spec/v1
oid sha256:53cb89a50fc4c99b9f8b14fc1adbe55b78422b8fe2869519bddb88fb150c2643
size 79424512
```

**Comment by OpenFunscripter** [comment]
I'm aware of this.
It's super annoying it requires a `git lfs pull` but the _free 1GB_ github LFS bandwidth is used up... so it would fail either way.
I will just include it back in the repository which is going to bloat the repo.

**Comment by Yoooi0** [comment]
Maybe just download it in github actions from: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
Or as an alternative you could add auto mpv download on startup to OFS itself.

**Comment by OpenFunscripter** [comment]
I'll investigate if there's a portable way of downloading & extracting it via cmake. 🤔

**Comment by OpenFunscripter** [comment]
This fixes the issue
