### ISSUE TITLE
REQUEST: Add collapsable groups to the lua gui api

### ISSUE THREAD

**Issue by UchihaPhantom** [OpenFunscripter/OFS#64]
Being able to group the module's UI into collapsable sections like the one in the Simulator configuration would be highly benefitial to the UX of the UI of many modules.
![image](https://user-images.githubusercontent.com/16101123/208414095-086e4c0d-2787-444b-aa71-982fb47e78bb.png)

**Comment by OpenFunscripter** [comment]
Ugh me using "fix" in the commit message auto closed the issue.
But it's added now
