### ISSUE TITLE
In 3.1 Actions get rendered below the tempo grid

### ISSUE THREAD

**Issue by UchihaPhantom** [OpenFunscripter/OFS#67]
![image](https://user-images.githubusercontent.com/16101123/208654509-fad268f5-d668-4538-ab22-f1780dea76e5.png)
As far as my memory severs in 2.0 and earlier actions were rendered on top of everything else - which made the view easier to read. I'd like that to be the case once again. I work mostly with Music Videos so that change would be really benefitial to my workflow.

**Comment by OpenFunscripter** [comment]
That's bad.
I reorded some stuff in the rendering and clearly should've tested the tempo overlay...

**Comment by OpenFunscripter** [comment]
I think it used to be that points where drawn on top but lines weren't.
I changed it so that both lines & points are drawn on top.
