### ISSUE TITLE
Chapter window padding when resizing window

### ISSUE THREAD

**Issue by scriptingsentinel** [OpenFunscripter/OFS#75]
The space after the chapter name textbox and before the second column called "Begin" is becoming wider and wider the more I resize the window.
Initial size:
![initialsize](https://user-images.githubusercontent.com/79535330/209698924-cc048d80-b787-4ce9-acc2-bc5977674bef.PNG)
Making the window a bit wider:
![resize1](https://user-images.githubusercontent.com/79535330/209698931-7e6d1b41-1456-4495-84ff-eed3290aac4b.PNG)
Making the window even more wider:
![resize2](https://user-images.githubusercontent.com/79535330/209698934-76bd9f08-fb04-409c-ab9f-5ad8edb7aabb.PNG)

**Comment by OpenFunscripter** [comment]
The text box now uses all available width.
I hope this will suffice.
