### ISSUE TITLE
Feature Request: Drop down list control for extensions

### ISSUE THREAD

**Issue by bornforthis2020** [OpenFunscripter/OFS#9]
I was wondering if it might be possible to add a drop down list control like the ones for "Scripting mode" and "Overlay mode" to the set of controls for extensions?
Thanks

**Comment by OpenFunscripter** [comment]
Sure I just don't know the best way to add this.
I could add something like below.
```Lua
ComboItems = {
  "Item1", -- [1]
  "Item2", -- [2]
  "Item3"  -- [3]
}
comboSelection = 1 -- 'Item1' is selected

function gui()
  comboSelection, selectionChanged = ofs.Combo("Label", comboSelection, ComboItems)
end


```

**Comment by bornforthis2020** [comment]
That looks good to me.
Another option could be something like below so that it's all contained in one variable?
```
myCombo = { selectedIndex = 1, items = { "item1",  "item2", "item3" } }
myCombo.selectedIndex, selectionChanged = ofs.Combo("Label", myCombo.selectedIndex, myCombo.items)
```

**Comment by bornforthis2020** [comment]
Thanks
